export const RESTORE_STATE = 'RESTORE_STATE'

export const SET_COUNTRIES = 'SET_COUNTRIES'
export const CHANGE_COUNTRY_SELECTION = 'CHANGE_COUNTRY_SELECTION'

export const SET_AVAILABLE_RECORDS = 'SET_AVAILABLE_RECORDS'

export const SET_DATASETS = 'SET_DATASETS'

export const SET_ORDERS = 'SET_ORDERS'
